package gstdata

import (
	"errors"
)

type property struct {
	validaionKey string
	flag         string
	allowedCols  []string
}

var myProps map[string]property = map[string]property{
	"bi": property{
		validaionKey: "Ymlfc2NyZWVu",
		flag:         "",
		allowedCols: []string{
			"gstin_number",
			"gst_insertion_date",
			"bussiness_fields_add",
			"state_name",
			"pincode",
			"bussiness_fields_add_district",
			"gstin_status",
		},
	},
	"weberp": property{
		validaionKey: "d2ViZXJwX3NjcmVlbg==",
		flag:         "",
		allowedCols: []string{
			"gstin_number",
			"gst_insertion_date",
			"bussiness_fields_add",
			"state_name",
			"pincode",
			"bussiness_fields_add_district",
			"gstin_status",
			"taxpayer_type",
		},
	},
	"buyermy": property{
		validaionKey: "e2WjAYKxY4OkdnWmch==",
		flag:         "",
		allowedCols: []string{
			"gstin_number",
			"gst_insertion_date",
			"bussiness_fields_add",
			"state_name",
			"pincode",
			"bussiness_fields_add_district",
			"gstin_status",
			"trade_name",
			"trade_name_replaced",
			"business_name",
			"business_name_replaced",
		},
	},
	"weberp2": property{
		validaionKey: "d2ViZXJwX3NjcmVlbg==",
		flag:         "2",
		allowedCols: []string{
			"gstin_number",
			"trade_name",
			"business_name",
			"gstin_status",
			"registration_date",
			"gst_insertion_date",
			"state_name",
			"pincode",
			"bussiness_fields_add",
			"bussiness_fields_pp",
			"business_constitution",
			"business_constitution_group_id",
			"business_activity_nature",
			"cancel_date",
			"taxpayer_type",
			"last_update_date",
			"centre_juri",
			"centre_jurisdiction_code",
			"state_juri",
			"state_jurisdiction_code",
			"building_name",
			"street",
			"location",
			"door_number",
			"floor_number",
			"lattitude",
			"longitude",
			"bussiness_place_add_nature",
			"building_name_addl",
			"street_addl",
			"location_addl",
			"door_number_addl",
			"state_name_addl",
			"floor_number_addl",
			"lattitude_addl",
			"longitude_addl",
			"pincode_addl",
			"nature_of_business_addl",
			"mobile_number",
			"email_id",
			"annual_turnover_slab",
			"gross_income",
			"percent_of_tax_payment_in_cash",
			"aadhar_authentication_status",
			"ekyc_verification_status",
			"core_business_activity_nature",
			"proprieter_name",
			"field_visit_conducted",
		},
	},
	"PAY": property{
		validaionKey: "d2WjAYKxY4OkdnWmch==",
		flag:         "",
		allowedCols: []string{
			"gstin_number",
			"trade_name",
			"business_name",
		},
	},
	"loans": property{
		validaionKey: "d2WjAYKxY4OkdnWmch==",
		flag:         "",
		allowedCols: []string{
			"pincode",
			"annual_turnover_slab",
			"registration_date",
		},
	},
	"loans2": property{
		validaionKey: "d2WjAYKxY4OkdnWmch==",
		flag:         "",
		allowedCols: []string{
			"business_name",
			"business_constitution",
			"business_constitution_group_id",
			"businesstype",
			"gstin_number",
			"trade_name",
			"business_name",
			"gstin_status",
			"registration_date",
			"gst_insertion_date",
			"state_name",
			"pincode",
			"bussiness_fields_add",
			"bussiness_fields_pp",
			"business_constitution",
			"business_activity_nature",
			"cancel_date",
			"taxpayer_type",
			"last_update_date",
			"centre_juri",
			"centre_jurisdiction_code",
			"state_juri",
			"state_jurisdiction_code",
			"building_name",
			"street",
			"location",
			"door_number",
			"floor_number",
			"lattitude",
			"longitude",
			"bussiness_place_add_nature",
			"building_name_addl",
			"street_addl",
			"location_addl",
			"door_number_addl",
			"state_name_addl",
			"floor_number_addl",
			"lattitude_addl",
			"longitude_addl",
			"pincode_addl",
			"nature_of_business_addl",
			"mobile_number",
			"email_id",
			"annual_turnover_slab",
			"gross_income",
			"percent_of_tax_payment_in_cash",
			"aadhar_authentication_status",
			"ekyc_verification_status",
			"core_business_activity_nature",
			"proprieter_name",
			"field_visit_conducted",
			"fk_glusr_usr_id",
			"date_of_verification",
			"updated_by",
			"bussiness_address_add",
			"business_address_pp",
			"business_name_pp",
			"fk_gstin_turnover_id",
			"gst_inserted_by",
			"date_of_filing",
			"filing_last_updation_date",
			"fk_gl_locality_id",
			"trade_name_replaced",
			"business_name_replaced",
			"business_fields_add_replaced",
			"business_address_add_replaced",
			"building_name_replaced",
			"street_replaced",
			"location_replaced",
			"door_number_replaced",
			"floor_number_replaced",
			"updated_by_screen",
			"hist_comments",
			"update_by_ip",
			"update_by_ip_country",
			"bussiness_fields_add_district",
			"bussiness_fields_pp_district",
			"turnover_year",
			"businesstype",
			"gst_glusr_turnover",
		},
	},
	"merpnsd": property{
		validaionKey: "bWVycF9zY3JlZW4=",
		flag:         "",
		allowedCols: []string{
			"business_name",
			"business_constitution",
			"business_constitution_group_id",
			"gstin_number",
			"trade_name",
			"gstin_status",
			"registration_date",
			"gst_insertion_date",
			"state_name",
			"pincode",
			"bussiness_fields_add",
			"bussiness_fields_pp",
			"business_constitution",
			"business_activity_nature",
			"cancel_date",
			"taxpayer_type",
			"last_update_date",
			"centre_juri",
			"centre_jurisdiction_code",
			"state_juri",
			"state_jurisdiction_code",
			"building_name",
			"street",
			"location",
			"door_number",
			"floor_number",
			"lattitude",
			"longitude",
			"bussiness_place_add_nature",
			"date_of_verification",
			"updated_by",
			"bussiness_address_add",
			"business_address_pp",
			"business_name_pp",
			"fk_gstin_turnover_id",
			"gst_inserted_by",
			"date_of_filing",
			"filing_last_updation_date",
			"fk_gl_locality_id",
		},
	},
	"gst_otp": property{
    validaionKey: "d2ViZXJwX3NjcmVlbg==",
    flag:         "",
    allowedCols: []string{
        "gstin_number",
        "mobile_number",
        "email_id",
        "gst_challan_mobile_by_befisc",
        "gst_challan_email_by_befisc",
    },
},
}

// ValidateProp ...
func ValidateProp(modid string, validationkey string, Flag string) ([]string, error) {

	if myProps[modid].validaionKey != validationkey || validationkey == "" || modid == "" {
		return nil, errors.New(errNotAuth)
	}

	if myProps[modid].flag == Flag {
		return myProps[modid].allowedCols, nil
	}
	return nil, errors.New(errNotAuth)
}
